# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='news.proto',
  package='newsProto',
  syntax='proto3',
  serialized_pb=_b('\n\nnews.proto\x12\tnewsProto\"\xd2\x01\n\x0bRequestNews\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x12\n\npageNumber\x18\x02 \x01(\x05\x12\x15\n\rresultPerPage\x18\x03 \x01(\x05\x12-\n\x06\x63orpus\x18\x04 \x01(\x0e\x32\x1d.newsProto.RequestNews.CORPUS\"X\n\x06\x43ORPUS\x12\x0b\n\x07SOCIETY\x10\x00\x12\x0c\n\x08POLITICS\x10\x01\x12\x0b\n\x07\x45\x43ONOMY\x10\x02\x12\x11\n\rINTERNATIONAL\x10\x03\x12\x0b\n\x07\x43ULTURE\x10\x04\x12\x06\n\x02IT\x10\x05\"\x8b\x01\n\x0cResponseNews\x12\x13\n\x0blinkUrlSha1\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07linkUrl\x18\x03 \x01(\t\x12\x11\n\tpublished\x18\x04 \x01(\t\x12\x10\n\x08\x63ontents\x18\x05 \x01(\t\x12\r\n\x05regDt\x18\x06 \x01(\t\x12\x12\n\nscrapingDt\x18\x07 \x01(\t2F\n\x04News\x12>\n\x07getList\x12\x16.newsProto.RequestNews\x1a\x17.newsProto.ResponseNews\"\x00\x30\x01\x42$\n\x0fwasabi.protocolB\tNewsProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)



_REQUESTNEWS_CORPUS = _descriptor.EnumDescriptor(
  name='CORPUS',
  full_name='newsProto.RequestNews.CORPUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOCIETY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLITICS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ECONOMY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNATIONAL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CULTURE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_REQUESTNEWS_CORPUS)


_REQUESTNEWS = _descriptor.Descriptor(
  name='RequestNews',
  full_name='newsProto.RequestNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='newsProto.RequestNews.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageNumber', full_name='newsProto.RequestNews.pageNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultPerPage', full_name='newsProto.RequestNews.resultPerPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corpus', full_name='newsProto.RequestNews.corpus', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTNEWS_CORPUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=236,
)


_RESPONSENEWS = _descriptor.Descriptor(
  name='ResponseNews',
  full_name='newsProto.ResponseNews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linkUrlSha1', full_name='newsProto.ResponseNews.linkUrlSha1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='newsProto.ResponseNews.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkUrl', full_name='newsProto.ResponseNews.linkUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='published', full_name='newsProto.ResponseNews.published', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='newsProto.ResponseNews.contents', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regDt', full_name='newsProto.ResponseNews.regDt', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scrapingDt', full_name='newsProto.ResponseNews.scrapingDt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=378,
)

_REQUESTNEWS.fields_by_name['corpus'].enum_type = _REQUESTNEWS_CORPUS
_REQUESTNEWS_CORPUS.containing_type = _REQUESTNEWS
DESCRIPTOR.message_types_by_name['RequestNews'] = _REQUESTNEWS
DESCRIPTOR.message_types_by_name['ResponseNews'] = _RESPONSENEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestNews = _reflection.GeneratedProtocolMessageType('RequestNews', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTNEWS,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:newsProto.RequestNews)
  ))
_sym_db.RegisterMessage(RequestNews)

ResponseNews = _reflection.GeneratedProtocolMessageType('ResponseNews', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSENEWS,
  __module__ = 'news_pb2'
  # @@protoc_insertion_point(class_scope:newsProto.ResponseNews)
  ))
_sym_db.RegisterMessage(ResponseNews)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017wasabi.protocolB\tNewsProtoP\001\242\002\003RTG'))

_NEWS = _descriptor.ServiceDescriptor(
  name='News',
  full_name='newsProto.News',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=380,
  serialized_end=450,
  methods=[
  _descriptor.MethodDescriptor(
    name='getList',
    full_name='newsProto.News.getList',
    index=0,
    containing_service=None,
    input_type=_REQUESTNEWS,
    output_type=_RESPONSENEWS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEWS)

DESCRIPTOR.services_by_name['News'] = _NEWS

# @@protoc_insertion_point(module_scope)
